// <auto-generated />
namespace Form2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class creation_classe_etudiant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creation_classe_etudiant));
        
        string IMigrationMetadata.Id
        {
            get { return "202501182020181_creation_classe_etudiant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
